package models

import (
	"database/sql"
)

//3#门车辆称重实体
type D3Weight struct {
	F_ID             string
	F_StdNo          string
	F_CarNo          string
	F_ProName        string
	F_Model          string
	F_UnitFrom       string
	F_Load           string
	F_UnitTo         string
	F_UnLoad         string
	F_Transport      string
	F_Driver         string
	F_Memo           string
	F_Number         string
	F_Type           string
	F_BanCi          string
	F_Gross          string
	F_Tare           string
	F_Net            string
	F_Deduct         string
	F_Fact           string
	F_Deduct2        string
	F_Fact2          string
	F_SettWgt        string
	F_Price          string
	F_Money          string
	F_Price2         string
	F_Money2         string
	F_SumMoney       string
	F_CardID         string
	F_Unit           string
	F_GrossTime      string
	F_TareTime       string
	F_BeginTime      string
	F_EndTime        string
	F_CNTime         string
	F_opManGross     string
	F_opManTare      string
	F_opMan          string
	F_edMan          string
	F_edTime         string
	F_RePrint        string
	F_PrTimes        string
	F_PrMan          string
	F_PrTime         string
	F_PrScaleName    string
	F_ScaleNameGross string
	F_ScaleNameTare  string
	F_ScaleNameNet   string
	F_IsCancel       string
	F_IsFinish       string
	F_CanUpdate      string
	F_IsUpdate       string
	F_DisEdit        string
	F_MacNo          string
	F_Status         string
	F_SerialNo       string
	F_SerialNoDay    string
	F_SerialNoMonth  string
	F_SerialNoYear   string
	F_WgtType        string
	F_YLStr01        string
	F_YLStr02        string
	F_YLStr03        string
	F_YLStr04        string
	F_YLStr05        string
	F_YLStr06        string
	F_YLStr07        string
	F_YLStr08        string
	F_YLStr09        string
	F_YLStr10        string
	F_YLFlt01        string
	F_YLFlt02        string
	F_YLFlt03        string
	F_YLFlt04        string
	F_YLFlt05        string
	F_YLFlt06        string
	F_YLFlt07        string
	F_YLFlt08        string
	F_YLFlt09        string
	F_YLFlt10        string
	F_YLInt01        string
	F_YLInt02        string
	F_YLInt03        string
	F_YLInt04        string
	F_YLInt05        string
	F_OrderNo        string
}

//3#门车辆称重实体
type D3WeightSql struct {
	F_ID             sql.NullString
	F_StdNo          sql.NullString
	F_CarNo          sql.NullString
	F_ProName        sql.NullString
	F_Model          sql.NullString
	F_UnitFrom       sql.NullString
	F_Load           sql.NullString
	F_UnitTo         sql.NullString
	F_UnLoad         sql.NullString
	F_Transport      sql.NullString
	F_Driver         sql.NullString
	F_Memo           sql.NullString
	F_Number         sql.NullString
	F_Type           sql.NullString
	F_BanCi          sql.NullString
	F_Gross          sql.NullString
	F_Tare           sql.NullString
	F_Net            sql.NullString
	F_Deduct         sql.NullString
	F_Fact           sql.NullString
	F_Deduct2        sql.NullString
	F_Fact2          sql.NullString
	F_SettWgt        sql.NullString
	F_Price          sql.NullString
	F_Money          sql.NullString
	F_Price2         sql.NullString
	F_Money2         sql.NullString
	F_SumMoney       sql.NullString
	F_CardID         sql.NullString
	F_Unit           sql.NullString
	F_GrossTime      sql.NullString
	F_TareTime       sql.NullString
	F_BeginTime      sql.NullString
	F_EndTime        sql.NullString
	F_CNTime         sql.NullString
	F_opManGross     sql.NullString
	F_opManTare      sql.NullString
	F_opMan          sql.NullString
	F_edMan          sql.NullString
	F_edTime         sql.NullString
	F_RePrint        sql.NullString
	F_PrTimes        sql.NullString
	F_PrMan          sql.NullString
	F_PrTime         sql.NullString
	F_PrScaleName    sql.NullString
	F_ScaleNameGross sql.NullString
	F_ScaleNameTare  sql.NullString
	F_ScaleNameNet   sql.NullString
	F_IsCancel       sql.NullString
	F_IsFinish       sql.NullString
	F_CanUpdate      sql.NullString
	F_IsUpdate       sql.NullString
	F_DisEdit        sql.NullString
	F_MacNo          sql.NullString
	F_Status         sql.NullString
	F_SerialNo       sql.NullString
	F_SerialNoDay    sql.NullString
	F_SerialNoMonth  sql.NullString
	F_SerialNoYear   sql.NullString
	F_WgtType        sql.NullString
	F_YLStr01        sql.NullString
	F_YLStr02        sql.NullString
	F_YLStr03        sql.NullString
	F_YLStr04        sql.NullString
	F_YLStr05        sql.NullString
	F_YLStr06        sql.NullString
	F_YLStr07        sql.NullString
	F_YLStr08        sql.NullString
	F_YLStr09        sql.NullString
	F_YLStr10        sql.NullString
	F_YLFlt01        sql.NullString
	F_YLFlt02        sql.NullString
	F_YLFlt03        sql.NullString
	F_YLFlt04        sql.NullString
	F_YLFlt05        sql.NullString
	F_YLFlt06        sql.NullString
	F_YLFlt07        sql.NullString
	F_YLFlt08        sql.NullString
	F_YLFlt09        sql.NullString
	F_YLFlt10        sql.NullString
	F_YLInt01        sql.NullString
	F_YLInt02        sql.NullString
	F_YLInt03        sql.NullString
	F_YLInt04        sql.NullString
	F_YLInt05        sql.NullString
	F_OrderNo        sql.NullString
}

type Test struct {
	F_ID    string
	F_StdNo string
	F_CarNo string
}
