package main
import (
	"fmt"
	"ifix.cbpc/cbpc/test/model"
)


func main(){
fmt.Println("hello world")
s:=model.NewStudent("tom",99)
fmt.Println(s)
fmt.Println((*s).Name)
fmt.Println(s.Name)
}
// Code generated by 'go generate'; DO NOT EDIT.