package main
import (
	"fmt"
	"ifix.cbpc/cbpc/test/model"
)

type Retriever interface {
	Get(url string) string
}

func main(){
var r Retriever
r=model.Retriever{"yy"}
s:=r.Get("123")
fmt.Println(s)

}
// Code generated by 'go generate'; DO NOT EDIT.