// Code generated by 'go generate'; DO NOT EDIT..
package main
import (
	"fmt"
	
)
const(
	s1=iota
	s2
	s3
	s4
	s5
)
func Counter() func(int)int {
	var x int=s1
return func(y int)int {
	x=x+y
	return x
}
}

func add(str ...string){
	s:=""
for _, v := range str {
	s+=v
}
fmt.Println(s)
}

func main(){
add("a","b","","c")
}
